name: Feature request
about: Suggest an idea for Mini ECU v2 or future bootloader/OTA phases
title: "[FEAT] "
labels: enhancement
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an enhancement!

  - type: textarea
    id: feature-desc
    attributes:
      label: Feature description
      description: "What would you like to see added or changed?"
      placeholder: "Add a second CAN frame for diagnostics..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: "Why is this feature useful? Who benefits from it?"
      placeholder: "This will make the project closer to a real automotive ECU by..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: "Have you considered alternative approaches?"
      placeholder: "Alternatively, we could just extend the CLI instead of CAN..."
    validations:
      required: false
